#pragma once


/************************************************/
/* This file was autogenerated by create_cpp.py */
/************************************************/


#include "tree.h"


class ProdExpr : public Node {
uint8_t byte;
public:
void produce(uint8_t byte, quick_lint_js::Memory_Resource &memory, std::vector<Node *> &queue);
void render(std::stringstream &out);
};



class ProdValue : public Node {
uint8_t byte;
public:
void produce(uint8_t byte, quick_lint_js::Memory_Resource &memory, std::vector<Node *> &queue);
void render(std::stringstream &out);
};



class ProdOperator : public Node {
uint8_t byte;
public:
void produce(uint8_t byte, quick_lint_js::Memory_Resource &memory, std::vector<Node *> &queue);
void render(std::stringstream &out);
};


